# Generated by Django 5.0.6 on 2024-06-28 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_compraaprobada_compraproducto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compraaprobada',
            name='delivery_method',
            field=models.CharField(choices=[('retiro', 'Retiro en Tienda'), ('despacho', 'Despacho a Domicilio')], default='retiro', max_length=20),
        ),
    ]
