# Generated by Django 5.0.6 on 2024-06-29 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_compraaprobada_delivery_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_compraaprobada', models.IntegerField()),
                ('usuario_username', models.CharField(max_length=150)),
                ('usuario_nombre', models.CharField(max_length=150)),
                ('usuario_apellido', models.CharField(max_length=150)),
                ('usuario_correo', models.EmailField(max_length=254)),
                ('usuario_telefono', models.CharField(max_length=15)),
                ('usuario_direccion', models.CharField(max_length=255)),
                ('usuario_rut', models.CharField(max_length=12)),
                ('pedido_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido_delivery_method', models.CharField(max_length=20)),
                ('pedido_estado', models.CharField(max_length=10)),
                ('productos', models.TextField()),
            ],
        ),
    ]
