# Generated by Django 5.0.6 on 2024-07-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_estadopedido_enviado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidofinal',
            name='enviada_a_vendedor',
            field=models.BooleanField(default=False),
        ),
    ]
