# Generated by Django 5.0.6 on 2024-07-11 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_voucher'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherEnviado',
            fields=[
                ('voucher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.voucher')),
                ('enviado', models.BooleanField(default=False)),
                ('enviado_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
