# Generated by Django 5.0.6 on 2024-07-12 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_voucherenviado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidofinal',
            name='enviada_a_vendedor',
            field=models.BooleanField(default=True),
        ),
    ]
