# Generated by Django 5.0.6 on 2024-07-12 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_pedidofinal_enviada_a_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('comprador', 'Comprador'), ('vendedor', 'Vendedor'), ('bodeguero', 'Bodeguero'), ('admin', 'Admin'), ('contador', 'Contador')], default='comprador', max_length=10),
        ),
    ]
