# Generated by Django 5.0.6 on 2024-06-30 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_detallepedido_id_compraaprobada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('preparado', 'Preparado'), ('despachado', 'Despachado'), ('listo_retiro', 'Listo para Retiro')], default='pendiente', max_length=16)),
                ('nota_bodeguero', models.TextField(blank=True, null=True)),
                ('id_detallepedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.detallepedido')),
            ],
        ),
    ]
