# Generated by Django 5.0.6 on 2024-06-30 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_estadopedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoEnviadoVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_username', models.CharField(max_length=255)),
                ('usuario_nombre', models.CharField(max_length=255)),
                ('usuario_apellido', models.CharField(max_length=255)),
                ('usuario_correo', models.CharField(max_length=255)),
                ('usuario_telefono', models.CharField(max_length=255)),
                ('usuario_direccion', models.CharField(max_length=255)),
                ('usuario_rut', models.CharField(max_length=255)),
                ('pedido_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido_delivery_method', models.CharField(max_length=255)),
                ('pedido_estado', models.CharField(choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], max_length=10)),
                ('productos', models.TextField()),
                ('nota_bodeguero', models.TextField(blank=True, null=True)),
                ('estado_bodeguero', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('preparado', 'Preparado'), ('despachado', 'Despachado'), ('listo_retiro', 'Listo para Retiro')], max_length=16)),
                ('enviado_a_vendedor', models.BooleanField(default=False)),
                ('id_estado_pedido', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.estadopedido')),
            ],
        ),
    ]
