# Generated by Django 5.0.6 on 2024-05-14 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_category_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Viaje',
        ),
    ]
