# Generated by Django 4.2.2 on 2024-05-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_productos_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, verbose_name='patente')),
                ('categoria', models.CharField(max_length=10, verbose_name='cate')),
                ('marca', models.CharField(max_length=10, verbose_name='Hora de inicio del Viaje')),
                ('nombre', models.CharField(max_length=10, verbose_name='noe')),
                ('precio', models.IntegerField(verbose_name='Capacidad de Pasajeros')),
                ('url_imagen', models.URLField(max_length=500, verbose_name='url_imagen')),
            ],
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
