# Generated by Django 5.0 on 2024-06-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_producto_categoria_alter_producto_codigo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='url_imagen',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
