# Generated by Django 5.0.6 on 2024-06-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_producto_url_imagen_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_online',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_tienda',
            field=models.IntegerField(default=0),
        ),
    ]
