# Generated by Django 5.0.6 on 2024-06-24 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_producto_stock_online_producto_stock_tienda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='stock_online',
            new_name='stock_onlines',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='stock_tienda',
            new_name='stock_tiendas',
        ),
    ]
